volumes:
  nexus_volume:
    external: true
services:
  fastapi:
    env_file:
      - .env
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://nexus_user:nexus@database/nexus_db
      SIGNING_KEY: d2b84cf92924b3fcccd4ee33669c2f2b208f29231c68c9493e64af5a23580fe2
      IMAGE_UPLOAD_TOKEN: ${IMAGE_UPLOAD_TOKEN}
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - database
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  database:
    image: postgres:15.3-bullseye
    volumes:
      - nexus_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: nexus
      POSTGRES_USER: nexus_user
      POSTGRES_DB: nexus_db
    ports:
      - 15432:5432
